# Generated by Django 5.0.2 on 2024-02-18 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Deal',
                'verbose_name_plural': 'Deals',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('fmv', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.CreateModel(
            name='ProjectDealThroughModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_credit_transfer_rate', models.DecimalField(decimal_places=2, max_digits=4)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clean_energy_deals.deal')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clean_energy_deals.project')),
            ],
            options={
                'verbose_name': 'Project and Deal',
                'verbose_name_plural': 'Projects and Deals',
            },
        ),
        migrations.AddField(
            model_name='deal',
            name='projects',
            field=models.ManyToManyField(through='clean_energy_deals.ProjectDealThroughModel', to='clean_energy_deals.project'),
        ),
    ]
